version: '3.9'

services:
  # Single container with both FastAPI and Celery
  web:
    build: .
    container_name: inhack-app
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - app-network
    # Health check for the web service
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  app-network:
    driver: bridge
